import type { Metadata } from "next";
import { Inter,Roboto } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/Providers/theme-provider";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ subsets: ["latin"],weight:["100",'300','400','500',"700","900"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className + " bg-gray-200/80 dark:bg-slate-900"}>
        <ThemeProvider attribute="class" defaultTheme="system">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
